import AppKit

/// Watches the general pasteboard and files what it finds into ``ClipboardHistoryStore``.
///
/// ## Polling, because there is nothing to observe
///
/// `NSPasteboard` posts no notification when its contents change — there is no API for it, and
/// there never has been. Every clipboard manager on the platform polls `changeCount`, which is a
/// single integer read costing a fraction of a microsecond. Twice a second is fast enough that a
/// copy is recorded before the user can reach ⌘V, and slow enough to be invisible in a power
/// profile.
///
/// The timer only exists while a Clipboard item is in the menu bar *and* something is enabled to
/// capture: with no Clipboard item MenuDock does not read the pasteboard at all, which is the
/// answer to "is this thing watching me?" that a user can actually verify by removing the item.
/// It also stops with the screen — shared with the icon animator and the metrics sampler through
/// ``DisplayActivityMonitor`` — since nothing can be copied on a locked or sleeping Mac.
@MainActor
final class ClipboardMonitor {
    private let history: ClipboardHistoryStore
    private let display: DisplayActivityMonitor
    private let displayListenerID = UUID()

    private var timer: Timer?
    private var timerInterval: Double = 0

    /// The settings currently in force, or `nil` when there is no Clipboard item.
    private var entry: ClipboardEntry?

    /// Last `changeCount` seen, so a poll that finds no change does no work at all.
    private var lastChangeCount = NSPasteboard.general.changeCount

    /// A `changeCount` produced by MenuDock itself putting an item *back*.
    ///
    /// Without this, choosing something from the history would immediately be re-captured as a
    /// brand new copy — which at best reshuffles the list under the user's cursor and at worst
    /// makes "paste the thing from three days ago" quietly rewrite today's history.
    private var suppressedChangeCount: Int?

    /// Base polling interval. Doubled in Low Power Mode.
    private static let interval: Double = 0.5

    /// Pasteboard types that mean "do not remember this".
    ///
    /// `ConcealedType` is the convention password managers use — 1Password, Bitwarden and
    /// Keychain Access all set it — and honouring it is the single most important thing this
    /// class does. The other two mark scratch copies that apps put on the pasteboard as an
    /// implementation detail and never intended a human to see again.
    private static let confidentialTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    init(history: ClipboardHistoryStore, display: DisplayActivityMonitor) {
        self.history = history
        self.display = display
        display.addListener(displayListenerID) { [weak self] in
            self?.updateTimer()
        }
    }

    isolated deinit {
        timer?.invalidate()
        display.removeListener(displayListenerID)
    }

    // MARK: - Configuration

    /// Applies the Clipboard item's settings, or `nil` if there is no longer one in the menu bar.
    ///
    /// Called on every configuration change rather than only at launch, because toggling capture
    /// off in Settings is exactly how the user expects polling to stop.
    func configure(_ entry: ClipboardEntry?) {
        let wasCapturing = isCapturing
        self.entry = entry

        // Retention is applied here as well as on capture, so shortening it in Settings takes
        // effect the moment the user picks the new value rather than on the next copy.
        if let entry {
            history.prune(retention: entry.retention, maxItems: entry.maxItems)
        }

        if isCapturing && !wasCapturing {
            // Take whatever is on the pasteboard right now as the first entry. Starting empty
            // after adding the item reads as broken — the user has plainly copied *something*
            // today — and the content hash means relaunching does not stack up duplicates.
            lastChangeCount = -1
        }
        updateTimer()
    }

    private var isCapturing: Bool {
        entry?.capturesAnything == true
    }

    // MARK: - Timer

    private func updateTimer() {
        guard isCapturing, display.isDisplayActive else {
            timer?.invalidate()
            timer = nil
            timerInterval = 0
            return
        }

        let interval = display.isLowPowerMode ? Self.interval * 2 : Self.interval
        if timer != nil, timerInterval == interval { return }

        timer?.invalidate()
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // `.common` so a copy made while a menu is open or a window is being dragged is still
        // recorded, and a generous tolerance so the wake-up rides along with other work.
        timer.tolerance = interval * 0.4
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
        timerInterval = interval

        poll()
    }

    // MARK: - Polling

    /// Marks the pasteboard's **current** contents as MenuDock's own, so they are not captured
    /// straight back.
    ///
    /// Called immediately *after* an item is put back, when `changeCount` has already advanced to
    /// the value the next poll will read. Reserving `changeCount + 1` instead — the reading that
    /// looks right until you trace it — is off by one in the worst available direction: the
    /// put-back is filed as a brand new copy, **and** whatever the user copies next is silently
    /// swallowed in its place. Both were observed before this was fixed.
    func ignoreCurrentContents() {
        suppressedChangeCount = NSPasteboard.general.changeCount
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        if let suppressed = suppressedChangeCount, suppressed == changeCount {
            suppressedChangeCount = nil
            return
        }
        // A stale suppression — our write was followed by someone else's before we polled — must
        // not silently swallow that other copy, so it is only ever honoured for the exact count.
        if let suppressed = suppressedChangeCount, changeCount > suppressed {
            suppressedChangeCount = nil
        }

        guard let entry, entry.capturesAnything else { return }

        if entry.ignoresConfidential, isConfidential(pasteboard) { return }
        guard let capture = capture(from: pasteboard, entry: entry) else { return }

        history.record(capture, retention: entry.retention, maxItems: entry.maxItems)
    }

    private func isConfidential(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return Self.confidentialTypes.contains { types.contains($0) }
    }

    // MARK: - Reading the pasteboard

    /// Turns the pasteboard's current contents into one capture, or `nil` if there is nothing
    /// here this entry wants.
    ///
    /// ## The order of these branches is the whole design
    ///
    /// A single copy usually puts several representations on the pasteboard at once, so "what did
    /// the user copy?" is a judgement call rather than a lookup. Files come first because a copy
    /// from Finder also carries the path as a string, and storing that string would give the user
    /// a row that pastes text where they expected a file. Text comes next, because a rich copy
    /// from a browser can carry an inline image the user never meant to single out. Images are
    /// therefore what is left — no files, and no text worth calling text.
    private func capture(from pasteboard: NSPasteboard, entry: ClipboardEntry) -> ClipboardCapture? {
        let source = NSWorkspace.shared.frontmostApplication

        if entry.capturesFiles, let capture = fileCapture(pasteboard) {
            return stamp(capture, with: source)
        }

        let string = pasteboard.string(forType: .string)
        let imageData = imagePayload(pasteboard)

        // An image copied from a web page arrives with its *URL* as the only text. Treating that
        // as a text copy would drop the picture on the floor, so a lone single-line URL beside
        // image data does not count as text.
        let textIsMeaningful = string.map { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
            ?? false
        let textIsJustALink = imageData != nil && string.map(Self.looksLikeBareURL) == true

        if entry.capturesText, textIsMeaningful, !textIsJustALink, let string {
            return stamp(textCapture(string, pasteboard: pasteboard), with: source)
        }

        if entry.capturesImages, let imageData, let capture = imageCapture(imageData) {
            return stamp(capture, with: source)
        }

        if entry.capturesText, textIsMeaningful, let string {
            return stamp(textCapture(string, pasteboard: pasteboard), with: source)
        }

        return nil
    }

    private func stamp(_ capture: ClipboardCapture, with source: NSRunningApplication?) -> ClipboardCapture {
        var result = capture
        result.sourceAppName = source?.localizedName
        result.sourceBundleIdentifier = source?.bundleIdentifier
        return result
    }

    // MARK: Text

    private func textCapture(_ string: String, pasteboard: NSPasteboard) -> ClipboardCapture {
        let textData = Data(string.utf8)
        // RTF is kept alongside the plain text, not instead of it, so the same row pastes with
        // formatting into Pages and without it into a terminal.
        let rtf = pasteboard.data(forType: .rtf)

        return ClipboardCapture(
            kind: .text(hasRichText: rtf != nil),
            preview: Self.previewText(string),
            contentHash: ClipboardCapture.hash(textData),
            byteCount: textData.count + (rtf?.count ?? 0),
            textData: textData,
            richTextData: rtf
        )
    }

    /// One line of a copy, for a list row: whitespace collapsed, and cut to a length the row can
    /// actually show. Done once at capture rather than per row draw.
    static func previewText(_ string: String) -> String {
        let collapsed = string
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
        guard collapsed.count > ClipboardHistoryStore.previewLimit else { return collapsed }
        return String(collapsed.prefix(ClipboardHistoryStore.previewLimit)) + "…"
    }

    /// Whether a string is nothing but a single web address.
    private static func looksLikeBareURL(_ string: String) -> Bool {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.contains(where: \.isWhitespace) else { return false }
        return trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://")
    }

    // MARK: Images

    /// PNG bytes for whatever image is on the pasteboard, preferring bytes that are *already* PNG.
    ///
    /// Re-encoding is skipped whenever it can be: a screenshot copy already carries PNG, and
    /// converting it would cost a few hundred milliseconds of main-thread time — on the timer
    /// that runs twice a second — to produce the bytes we were handed. TIFF-only pasteboards
    /// (older apps, and Preview) do have to be converted, but that is once per copy, not per poll.
    private func imagePayload(_ pasteboard: NSPasteboard) -> Data? {
        if let png = pasteboard.data(forType: .png) { return png }
        guard let tiff = pasteboard.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private func imageCapture(_ png: Data) -> ClipboardCapture? {
        guard let rep = NSBitmapImageRep(data: png) else { return nil }
        // `pixelsWide` rather than `size`, which is in points and reports a Retina screenshot at
        // half its real dimensions.
        let width = rep.pixelsWide
        let height = rep.pixelsHigh
        guard width > 0, height > 0 else { return nil }

        return ClipboardCapture(
            kind: .image(pixelWidth: width, pixelHeight: height),
            preview: "\(width) × \(height)",
            contentHash: ClipboardCapture.hash(png),
            byteCount: png.count,
            imageData: png,
            thumbnailData: Self.thumbnail(from: rep)
        )
    }

    /// A small PNG for the list row, so showing the history never decodes full-size images.
    private static func thumbnail(from rep: NSBitmapImageRep) -> Data? {
        let limit = ClipboardHistoryStore.thumbnailPixels
        let scale = min(limit / CGFloat(rep.pixelsWide), limit / CGFloat(rep.pixelsHigh), 1)
        let width = max(Int((CGFloat(rep.pixelsWide) * scale).rounded()), 1)
        let height = max(Int((CGFloat(rep.pixelsHigh) * scale).rounded()), 1)

        guard let target = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: width, pixelsHigh: height,
            bitsPerSample: 8, samplesPerPixel: 4,
            hasAlpha: true, isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0, bitsPerPixel: 0
        ) else { return nil }
        target.size = NSSize(width: width, height: height)

        NSGraphicsContext.saveGraphicsState()
        defer { NSGraphicsContext.restoreGraphicsState() }
        guard let context = NSGraphicsContext(bitmapImageRep: target) else { return nil }
        NSGraphicsContext.current = context
        context.imageInterpolation = .high
        rep.draw(in: NSRect(x: 0, y: 0, width: width, height: height))
        context.flushGraphics()

        return target.representation(using: .png, properties: [:])
    }

    // MARK: Files

    private func fileCapture(_ pasteboard: NSPasteboard) -> ClipboardCapture? {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
              !urls.isEmpty else { return nil }

        let paths = urls.map(\.path)
        let names = urls.map(\.lastPathComponent).joined(separator: ", ")

        return ClipboardCapture(
            kind: .files(paths: paths),
            preview: Self.previewText(names),
            // Hashed on the paths, so re-copying the same files promotes the existing row rather
            // than adding another identical one.
            contentHash: ClipboardCapture.hash(Data(paths.joined(separator: "\n").utf8)),
            byteCount: 0
        )
    }
}
